services:
  reverse-proxy:
    container_name: "reverse-proxy"
    hostname: "localhost"
    build: .
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/log:/var/log/nginx/
  app:
    container_name: "api"
    hostname: "localhost"
    build: ./api
    expose:
      - "3000"