services:
  reverse-proxy:
    container_name: "reverse-proxy"
    hostname: "localhost"
    build: .
    ports:
      - 80:80
      - 443:443
  app:
    container_name: "app"
    hostname: "localhost"
    build: ./app
    ports:
      - 3000:3000